#ifndef _CLI_CONST_H_
#define _CLI_CONST_H_

#define BLOCK_SIZE 2
#define NEXT_FIG_BLOCK_SIZE 4

#define HELP_SCREEN_X_SIZE 27
#define HELP_SCREEN_Y_SIZE 22
#define HELP_SCREEN_X_OFFSET 0
#define HELP_SCREEN_Y_OFFSET 0

#define GAME_SCREEN_X_SIZE (10 * BLOCK_SIZE + 2)
#define GAME_SCREEN_Y_SIZE 22
#define GAME_SCREEN_X_OFFSET (HELP_SCREEN_X_SIZE + 1)
#define GAME_SCREEN_Y_OFFSET 0

#define GAME_INFO_SCREEN_X_SIZE 22
#define GAME_INFO_SCREEN_Y_SIZE 22
#define GAME_INFO_SCREEN_X_OFFSET (HELP_SCREEN_X_SIZE + GAME_SCREEN_X_SIZE + 2)
#define GAME_INFO_SCREEN_Y_OFFSET 0

#define FIG_COORD_X 2
#define FIG_COORD_Y 4

#define START_SCREEN_X_SIZE 16
#define START_SCREEN_Y_SIZE 6
#define START_SCREEN_X_OFFSET                                                  \
  GAME_SCREEN_X_OFFSET + (GAME_SCREEN_X_SIZE - START_SCREEN_X_SIZE) / 2
#define START_SCREEN_Y_OFFSET (GAME_SCREEN_Y_SIZE - START_SCREEN_Y_SIZE) / 2

#define PAUSE_SCREEN_X_SIZE 16
#define PAUSE_SCREEN_Y_SIZE 6
#define PAUSE_SCREEN_X_OFFSET                                                  \
  GAME_SCREEN_X_OFFSET + (GAME_SCREEN_X_SIZE - PAUSE_SCREEN_X_SIZE) / 2
#define PAUSE_SCREEN_Y_OFFSET (GAME_SCREEN_Y_SIZE - PAUSE_SCREEN_Y_SIZE) / 2

#define GAME_OVER_SCREEN_X_SIZE 16
#define GAME_OVER_SCREEN_Y_SIZE 9
#define GAME_OVER_SCREEN_X_OFFSET                                              \
  GAME_SCREEN_X_OFFSET + (GAME_SCREEN_X_SIZE - GAME_OVER_SCREEN_X_SIZE) / 2
#define GAME_OVER_SCREEN_Y_OFFSET                                              \
  (GAME_SCREEN_Y_SIZE - GAME_OVER_SCREEN_Y_SIZE) / 2

#endif
